#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("MovieSearch.Droid.Resource", IsApplication=true)]

namespace MovieSearch.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int minTextSize = 2130771968;
			
			// aapt resource value: 0x7f010001
			public const int precision = 2130771969;
			
			// aapt resource value: 0x7f010002
			public const int sizeToFit = 2130771970;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040001
			public const int green = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int saddlebrown = 2130968576;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int btTdmkgIvOi0FFip1sPuZI2oQG6 = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int marilyn_monroe = 2130837506;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f06000b
			public const int actors = 2131099659;
			
			// aapt resource value: 0x7f060002
			public const int getMovieButton = 2131099650;
			
			// aapt resource value: 0x7f060004
			public const int imageView1 = 2131099652;
			
			// aapt resource value: 0x7f060000
			public const int informationText = 2131099648;
			
			// aapt resource value: 0x7f060007
			public const int listItem = 2131099655;
			
			// aapt resource value: 0x7f060001
			public const int movieTitleInputField = 2131099649;
			
			// aapt resource value: 0x7f060008
			public const int poster = 2131099656;
			
			// aapt resource value: 0x7f06000a
			public const int ratings = 2131099658;
			
			// aapt resource value: 0x7f060003
			public const int resultText = 2131099651;
			
			// aapt resource value: 0x7f060006
			public const int tagline = 2131099654;
			
			// aapt resource value: 0x7f060005
			public const int title = 2131099653;
			
			// aapt resource value: 0x7f060009
			public const int year = 2131099657;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int MovieDetail = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int MovieListItem = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int app_name = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] AutofitTextView = new int[] {
					2130771968,
					2130771969,
					2130771970};
			
			// aapt resource value: 0
			public const int AutofitTextView_minTextSize = 0;
			
			// aapt resource value: 1
			public const int AutofitTextView_precision = 1;
			
			// aapt resource value: 2
			public const int AutofitTextView_sizeToFit = 2;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
